<?php
/**
 * @var Magento\Framework\View\Element\Template $block
 * @var ScienceSoft\BookFrontendUi\ViewModel\BookViewModel $viewModel
 */
$viewModel = $block->getViewModel();
?>
<table>
    <tr>
        <th class="id">Id</th>
        <th class="name">Name</th>
        <th>Content</th>
        <th>Genre</th>
        <th>Date write</th>
        <th>Count pages</th>

    </tr>
<?php foreach ($viewModel->getBookCollection() as $book) : ?>
    <tr>
        <td><?= $book->getId() ?></td>
        <td><?= $book->getName() ?></td>
        <td><?= $book->getContent() ?></td>
        <td><?= $book->getGenre() ?></td>
        <td><?= $book->getDateWrite() ?></td>
        <td><?= $book->getCountPages() ?></td>
    </tr>
<?php endforeach; ?>
</table>

<?php var_dump($viewModel->getOneBook()->getData()); ?>
