<?php
///**
// * @var \ScienceSoft\BookFrontendUi\Block\BookFrontendUi $block
// */

/**
 * @var Magento\Framework\View\Element\Template $block
 * @var ScienceSoft\BookFrontendUi\ViewModel\BookViewModel $viewModel
 */
//$viewModel = $block->getData('view_model');

//$viewModel->getId();
$viewModel = $block->getViewModel();
//$viewModel = $block->getViewModel();
?>
<h1><?= $block->escapeHtml($viewModel->getSomething()); ?></h1>
<?= $viewModel->getSomething()?>

<table>
    <tr>
        <th class="id">Id</th>
        <th class="name">Name</th>
        <th>Content</th>
        <th>Genre</th>
        <th>Date write</th>
        <th>Count pages</th>

    </tr>
<?php foreach ($viewModel->getBookCollection() as $book) : ?>
    <tr>
        <td><?= $book->getId() ?></td>
        <td><?= $book->getName() ?></td>
        <td><?= $book->getContent() ?></td>
        <td><?= $book->getGenre() ?></td>
        <td><?= $book->getDate_write() ?></td>
        <td><?= $book->getCount_pages() ?></td>
    </tr>
<?php endforeach; ?>
</table>
