<?php
// IN CATALOG
/**
 * @var ScienceSoft\BookFrontendUi\Block\BookFrontendUi $block
 */
?>
<h1>Here we use repository</h1>
<table>
    <tr>
        <th class="id">Id</th>
        <th class="name">Name</th>
        <th>Content</th>
        <th>Genre</th>
        <th>Date write</th>
        <th>Count pages</th>

    </tr>
    <?php foreach ($block->getBookCollection() as $book) : ?>
        <tr>
            <td><?= $book->getId() ?></td>
            <td><?= $book->getName() ?></td>
            <td><?= $book->getContent() ?></td>
            <td><?= $book->getGenre() ?></td>
            <td><?= $book->getDate_write() ?></td>
            <td><?= $book->getCount_pages() ?></td>
        </tr>
    <?php endforeach; ?>
</table>
